import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav
          className={
            inter.className +
            "isolate z-10 w-full p-4 top-0 fixed backdrop-blur-md backdrop-brightness-110 bg-white/50"
          }
        >
          <Link href="" className="font-extralight inline text-4xl">
            Ocean.
          </Link>
          <div className="ml-10 inline-flex flex-wrap gap-10 pt-4">
            <button className="nav-link">
              <div>Waveform</div>
            </button>
            <button className="nav-link">
              <div>Contact</div>
            </button>
            <Link
              href="https://en.wikipedia.org/wiki/Ocean"
              className="nav-link"
            >
              <div>About</div>
            </Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
